using System.Collections.Generic;

namespace BR.Core.Models
{
    public static class Places
    {
        public static IEnumerable<string> Countries
        {
            get
            {
                return new[] {
                    "Albania",
                    "Azerbaijan",
                    "Belgium",
                    "Bulgaria",
                    "Croatia",
                    "Cyprus",
                    "Denmark",
                    "Estonia",
                    "Faroe Islands",
                    "Finland",
                    "France",
                    "Georgia",
                    "Germany",
                    "Greece",
                    "Iceland",
                    "Ireland",
                    "Italy",
                    "Latvia",
                    "Lithuania",
                    "Malta",
                    "Monaco",
                    "Montenegro",
                    "Netherlands",
                    "Norway",
                    "Poland",
                    "Portugal",
                    "Romania",
                    "Spain",
                    "Sweden",
                    "Ukraine",
                    "United Kingdom",
                    "Algeria",
                    "Angola",
                    "Benin",
                    "Cameroon",
                    "Cape Verde",
                    "Comoros",
                    "Democratic Republic of the Congo",
                    "Côte d'Ivoire (Ivory Coast)",
                    "Djibouti",
                    "Egypt",
                    "Equatorial Guinea",
                    "Eritrea",
                    "Gabon",
                    "Gambia",
                    "Ghana",
                    "Guinea",
                    "Guinea-Bissau",
                    "Kenya",
                    "Liberia",
                    "Libya",
                    "Madagascar",
                    "Mauritania",
                    "Mauritius",
                    "Mayotte",
                    "Marocco",
                    "Mozambique",
                    "Namibia",
                    "Nigeria",
                    "Reunion",
                    "Republic of the Congo",
                    "Saint Helena Island",
                    "Sao Tome and Principe",
                    "Senegal",
                    "Seychelles",
                    "Sierra Leone",
                    "Somalia",
                    "South Africa",
                    "Sudan",
                    "Tanzania",
                    "Togo",
                    "Tunisia",
                    "Anguilla",
                    "Antigua and Barbuda",
                    "Bahamas",
                    "Barbados",
                    "Belize",
                    "Bermuda",
                    "British Virgin Islands",
                    "Canada",
                    "Cayman Islands",
                    "Costa Rica",
                    "Cuba",
                    "Dominica",
                    "Dominican Republic",
                    "El Salvador",
                    "Greenland",
                    "Grenada",
                    "Guadeloupe",
                    "Guatemala",
                    "Haiti",
                    "Honduras",
                    "Jamaica",
                    "Martinique",
                    "Mexico",
                    "Nicaragua",
                    "Panama",
                    "Puerto Rico",
                    "Saint Kitts and Nevis",
                    "Saint Lucia",
                    "Saint Pierre and Miquelon",
                    "Saint Vincent and the Grenadines",
                    "Trinidad and Tobago",
                    "Turks and Caicos Islands",
                    "United States",
                    "Argentina",
                    "Aruba",
                    "Brazil",
                    "Chile",
                    "Colombia",
                    "Ecuador",
                    "Falkland Islands",
                    "French Guiana",
                    "Guyana",
                    "Peru",
                    "Suriname",
                    "Uruguay",
                    "Venezuela",
                    "Australia",
                    "Cook Islands",
                    "Fiji",
                    "French Polynesia",
                    "Kiribati",
                    "Marshall Islands",
                    "Micronesia",
                    "Nauru",
                    "New Caledonia",
                    "New Zealand",
                    "Niue",
                    "Palau",
                    "Papua New Guinea",
                    "Samoa",
                    "Solomon Islands",
                    "Tonga",
                    "Tuvalu",
                    "Vanuatu",
                    "Bahrain",
                    "Bangladesh",
                    "Brunei Darussalam",
                    "Cambodia",
                    "China",
                    "East Timor",
                    "India",
                    "Indonesia",
                    "Iran",
                    "Iraq",
                    "Israel",
                    "Japan",
                    "Jordan",
                    "Kuwait",
                    "Lebanon",
                    "Malaysia",
                    "Maldives",
                    "Myanmar (Burma)",
                    "North Korea",
                    "Oman",
                    "Pakistan",
                    "Philippines",
                    "Quatar",
                    "Russia",
                    "Saudi Arabia",
                    "Singapore",
                    "South Korea",
                    "Sri Lanca",
                    "Sirya",
                    "Taiwan",
                    "Thailand",
                    "Turkey",
                    "United Arab Emirates",
                    "Vietnam",
                    "Yemen"
                };
            }
        }
    }
}
