service: iam

provider:
  name: aws
  runtime: dotnetcore2.1
  region: eu-central-1

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: BR.Iam::BR.Iam.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY